global:
  environment: production

images:
  registry: dinhcam89
  pullPolicy: IfNotPresent
  tag: v0.0.1

services:
  apiGateway:
    name: api-gateway
    port: 9000
    replicas: 1
  frontend:
    name: frontend
    port: 80
    replicas: 1
  identityService:
    name: identity
    port: 8087
    replicas: 1
  inventoryService:
    name: inventory
    port: 8082
    replicas: 1
  notificationService:
    name: notification
    port: 8083
    replicas: 1
  orderService:
    name: order
    port: 8081
    replicas: 1
  productService:
    name: product
    port: 8080
    replicas: 1

config:
  common:
    PRODUCT_SERVICE_URL: "http://product-service.app.svc.cluster.local:8080"
    ORDER_SERVICE_URL: "http://order-service.app.svc.cluster.local:8081"
    INVENTORY_SERVICE_URL: "http://inventory-service.app.svc.cluster.local:8082"
    SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.app.svc.cluster.local:29092"
    IDENTITY_SERVICE_URL: "http://identity-service.app.svc.cluster.local:8087"
  
  identityService:
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.app.svc.cluster.local:3306/identity_service"
  
  inventoryService:
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.app.svc.cluster.local:3306/inventory_service"
  
  notificationService:
    SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.app.svc.cluster.local:8081"
  
  orderService:
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql.app.svc.cluster.local:3306/order_service"
    SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.app.svc.cluster.local:8081"
  
  productService:
    SPRING_DATA_MONGODB_URI: "mongodb://root:password@mongodb.app.svc.cluster.local:27017/product-service?authSource=admin"